---
name: ${PROJECT_NAME}
services:
  bind9:
    hostname: ${PROJECT_NAME}
    domainname: ${LOCAL_DOMAIN}
    image: internetsystemsconsortium/bind9:9.20
    container_name: ${PROJECT_NAME}
    ports:
      - "${BIND9_HOST_PORT}:53/udp"
      - "${BIND9_HOST_PORT}:53/tcp"
    volumes:
      - bind9-conf:/etc/bind
      - bind9-cache:/var/cache/bind
      - bind9-lib:/var/lib/bind
      - bind9-log:/var/log
    restart: unless-stopped
    networks:
      ix-portainer_default:

volumes:
  bind9-conf:
  bind9-cache:
  bind9-lib:
  bind9-log:

networks:
  ix-portainer_default:
    external: true
