---
name: ${PROJECT_NAME}
services:
  ns1:
    hostname: ${PROJECT_NAME}.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    container_name: ${PROJECT_NAME}
    image: internetsystemsconsortium/bind9:9.20
    volumes:
      - conf:/etc/bind
      - cache:/var/cache/bind
      - lib:/var/lib/bind
      - log:/var/log
    restart: unless-stopped
    #dns: 127.0.0.1
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${NS_IP}

volumes:
  conf:
  cache:
  lib:
  log:

networks:
  net1:
    attachable: true
    driver: ipvlan
    driver_opts:
      parent: eno2
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${LAN_CIDR}
          gateway: ${LAN_GW}
    name: ${LAN_NAME}
