---
name: ${PROJECT_NAME}
services:
  ns1:
    hostname: ${PROJECT_NAME}.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    container_name: ${PROJECT_NAME}
    image: internetsystemsconsortium/bind9:9.20
    restart: unless-stopped
    volumes:
      - conf:/etc/bind
      - cache:/var/cache/bind
      - lib:/var/lib/bind
      - log:/var/log
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

volumes:
  conf:
  cache:
  lib:
  log:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
