---
services:
  pgadmin:
    hostname: pgadmin.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - data:/var/lib/pgadmin
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

volumes:
  data:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
