---
services:
  freeipa:
    hostname: ${COMPOSE_PROJECT_NAME}.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    image: freeipa/freeipa-server:rocky-9
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    environment:
      IPA_SERVER_HOSTNAME: ${COMPOSE_PROJECT_NAME}.${LOCAL_DOMAIN}
      IPA_REALM: ${KRB5_REALM}
      IPA_DOMAIN: ${LOCAL_DOMAIN}
      IPA_ADMIN_PASSWORD: "${IPA_ADMIN_PASSWORD}"
      IPA_DNS_FORWARDER: "8.8.8.8"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      net1:
        ipv4_address: ${THIS_IP} 

volumes:
  data:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
