---
name: apt-cacher-ng
services:
  apt-cacher-ng:
    hostname: aptcache.${LOCAL_DOMAIN}
    domainname: ${LOCAL_DOMAIN}
    container_name: apt-cacher-ng
    image: dmbrownlee/apt-cacher-ng:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - cache:/var/cache/apt-cacher-ng
      - log:/var/log/apt-cacher-ng
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

volumes:
  cache:
  log:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
