---
version: "3.8"
services:
  registry:
    hostname: ${COMPOSE_PROJECT_NAME}
    domainname: ${LOCAL_DOMAIN}
    image: registry:latest
    restart: unless-stopped
    environment:
      - REGISTRY_HTTP_SECRET=${SECRET}
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

volumes:
  registry-data:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
