---
services:
  homepage:
    hostname: homepage
    domainname: ${LOCAL_DOMAIN}
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS="homepage.${LOCAL_DOMAIN}"
    volumes:
      - config:/app/config
      - images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}
  
volumes:
  config:
  images:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
