---
name: ${PROJECT_NAME}
services:
  ns1:
    hostname: ns1
    domainname: ${LOCAL_DOMAIN}
    image: internetsystemsconsortium/bind9:9.20
    volumes:
      - ns1-conf:/etc/bind
      - ns1-cache:/var/cache/bind
      - ns1-lib:/var/lib/bind
      - ns1-log:/var/log
    restart: unless-stopped
    networks:
      net1:
        ipv4_address: ${NS1_IP}

  apt-cacher-ng:
    hostname: aptcache
    image: dmbrownlee/apt-cacher-ng:latest
    build:
      context: .
      dockerfile: apt-cacher-ng/Dockerfile
    container_name: aptcache
    volumes:
      - aptcache-cache:/var/cache/apt-cacher-ng
      - aptcache-log:/var/log/apt-cacher-ng
    networks:
      net1:
        ipv4_address: ${APTCACHE_IP}

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84  # optional
      - NGINX_PORT=80  # optional
      - WEB_APP_PORT=3001  # optional
    volumes:
      - netbootxyz-conf:/config  # optional
      - netbootxyz-assets:/assets  # optional
    restart: unless-stopped
    networks:
      net1:
        ipv4_address: ${NETBOOT_IP}

  mail:
    hostname: mail.${LOCAL_DOMAIN}
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mail
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      - mail-conf:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      net1:
        ipv4_address: ${MAIL_IP}

  homepage:
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      net1:
        ipv4_address: ${HOMEPAGE_IP}
    volumes:
      - homepage-config:/app/config
      - homepage-images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  
volumes:
  ns1-conf:
  ns1-cache:
  ns1-lib:
  ns1-log:
  aptcache-cache:
  aptcache-log:
  netbootxyz-conf:
  netbootxyz-assets:
  mail-data:
  mail-state:
  mail-logs:
  mail-conf:
  homepage-config:
  homepage-images:

networks:
  net1:
    attachable: true
    driver: ipvlan
    driver_opts:
      parent: eno2
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${NET1_CIDR}
          ip_range: ${NET1_POOL_CIDR}
          gateway: ${NET1_GW}
    name: ${NET1_NAME}
