---
name: netbootxyz
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.47  # optional
      - NGINX_PORT=80  # optional
      - WEB_APP_PORT=3000  # optional
    volumes:
      - netbootxyz-conf:/config  # optional
      - netbootxyz-assets:/assets  # optional
    ports:
      - 8101:3000  # optional, should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8102:80  # optional, should match ${NGINX_PORT} variable above.
    restart: unless-stopped

volumes:
  netbootxyz-conf:
  netbootxyz-assets:
